### ISSUE TITLE
slow mods downloading in the 300kb/s first time connecting on local network

### ISSUE THREAD

**Issue by Vegas10128** [SathiraSriSathsara/cod4x-linux-server#2]
when connection to local server using console the first time startup will download from directory mods/yourmod 
that download takes a very long time over local network. 
Is there a start.sh command I can use to make the download speed faster for first time connections?

**Comment by SathiraSriSathsara** [comment]
Hello  @Vegas10128,

Thank you for your patience. Fast downloading is not configured by default in the server setup you have to configure it manually by editing your server.cfg file. You can configure an HTTP web server to download mod files in your server to speed up the downloading process. 

This video will help you to do that: https://www.youtube.com/watch?v=inirsIk9P4Y&t=272s

If you need any assistance I'm available in Discord reach me at: samtm_ or join our Discord server (https://discord.gg/rK9Uk3fBEn) and open a ticket.
